FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY target/x86_64-unknown-linux-musl/release/netplane-server netplane-server

ENV RUST_LOG=debug
EXPOSE 8080
EXPOSE 5050/udp
EXPOSE 5050/tcp
ENTRYPOINT ["./netplane-server"]
