[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.ios]
script = '''
cargo build --lib --target aarch64-apple-ios --release
cargo build --lib --target x86_64-apple-ios --release
'''

[tasks.android]
script = '''
export ANDROID_CLANG="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/bin"
cargo build --lib --target x86_64-linux-android --release --config "target.x86_64-linux-android.linker='$ANDROID_CLANG/x86_64-linux-android21-clang'"
'''

[tasks.musl]
script = '''
cargo build --target=x86_64-unknown-linux-musl --release
'''