// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/client.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


                /// Main entrypoint of the Rust API
                class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
                  @internal
                  static final instance = RustLib._();

                  RustLib._();

                  /// Initialize flutter_rust_bridge
                  static Future<void> init({
                    RustLibApi? api,
                    BaseHandler? handler,
                    ExternalLibrary? externalLibrary,
                    bool forceSameCodegenVersion = true,
                  }) async {
                    await instance.initImpl(
                      api: api,
                      handler: handler,
                      externalLibrary: externalLibrary,
                      forceSameCodegenVersion: forceSameCodegenVersion,
                    );
                  }

                  /// Initialize flutter_rust_bridge in mock mode.
                  /// No libraries for FFI are loaded.
                  static void initMock({
                    required RustLibApi api,
                  }) {
                    instance.initMockImpl(
                      api: api,
                    );
                  }

                  /// Dispose flutter_rust_bridge
                  ///
                  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
                  /// is automatically disposed when the app stops.
                  static void dispose() => instance.disposeImpl();

                  @override
                  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

                  @override
                  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

                  @override
                  Future<void> executeRustInitializers() async {
                    await api.crateApiClientInitApp();

                  }

                  @override
                  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

                  @override
                  String get codegenVersion => '2.12.0';

                  @override
                  int get rustContentHash => 972737083;

                  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
                    stem: 'rust_lib_netplane',
                    ioDirectory: 'rust/target/release/',
                    webPrefix: 'pkg/',
                    wasmBindgenName: 'wasm_bindgen',
                  );
                }
                

                abstract class RustLibApi extends BaseApi {
                  Future<void> crateApiClientAuthenticate({required NetplaneConfig config });

Stream<ConnectionEvent> crateApiClientConnect({required NetplaneConfig config });

Future<void> crateApiClientDisconnect();

Future<void> crateApiClientGenerateKeys({required String publicKeyPath , required String privateKeyPath });

Future<void> crateApiClientInitApp();

Future<void> crateApiClientInitLogger({required int logFormat });


                }
                

                class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
                  RustLibApiImpl({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  @override Future<void> crateApiClientAuthenticate({required NetplaneConfig config })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_box_autoadd_netplane_config(config, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiClientAuthenticateConstMeta,
            argValues: [config],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiClientAuthenticateConstMeta => const TaskConstMeta(
            debugName: "authenticate",
            argNames: ["config"],
        );
        

@override Stream<ConnectionEvent> crateApiClientConnect({required NetplaneConfig config })  { 
            final sink = RustStreamSink<ConnectionEvent>();
            unawaited(handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_box_autoadd_netplane_config(config, serializer);
sse_encode_StreamSink_connection_event_Sse(sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiClientConnectConstMeta,
            argValues: [config, sink],
            apiImpl: this,
        )));
            return sink.stream;
             }


        TaskConstMeta get kCrateApiClientConnectConstMeta => const TaskConstMeta(
            debugName: "connect",
            argNames: ["config", "sink"],
        );
        

@override Future<void> crateApiClientDisconnect()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiClientDisconnectConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiClientDisconnectConstMeta => const TaskConstMeta(
            debugName: "disconnect",
            argNames: [],
        );
        

@override Future<void> crateApiClientGenerateKeys({required String publicKeyPath , required String privateKeyPath })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(publicKeyPath, serializer);
sse_encode_String(privateKeyPath, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateApiClientGenerateKeysConstMeta,
            argValues: [publicKeyPath, privateKeyPath],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiClientGenerateKeysConstMeta => const TaskConstMeta(
            debugName: "generate_keys",
            argNames: ["publicKeyPath", "privateKeyPath"],
        );
        

@override Future<void> crateApiClientInitApp()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiClientInitAppConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiClientInitAppConstMeta => const TaskConstMeta(
            debugName: "init_app",
            argNames: [],
        );
        

@override Future<void> crateApiClientInitLogger({required int logFormat })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_i_32(logFormat, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiClientInitLoggerConstMeta,
            argValues: [logFormat],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiClientInitLoggerConstMeta => const TaskConstMeta(
            debugName: "init_logger",
            argNames: ["logFormat"],
        );
        



                  @protected AnyhowException dco_decode_AnyhowException(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return AnyhowException(raw as String); }

@protected RustStreamSink<ConnectionEvent> dco_decode_StreamSink_connection_event_Sse(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
throw UnimplementedError(); }

@protected String dco_decode_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as String; }

@protected bool dco_decode_bool(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as bool; }

@protected NetplaneConfig dco_decode_box_autoadd_netplane_config(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_netplane_config(raw); }

@protected ConnectionEvent dco_decode_connection_event(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
switch (raw[0]) {
                case 0: return ConnectionEvent_Connecting();
case 1: return ConnectionEvent_Connected(ipAddr: dco_decode_String(raw[1]),netmask: dco_decode_String(raw[2]),);
case 2: return ConnectionEvent_Disconnected();
case 3: return ConnectionEvent_Error(dco_decode_String(raw[1]),);
                default: throw Exception("unreachable");
            } }

@protected int dco_decode_i_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Uint8List; }

@protected NetplaneConfig dco_decode_netplane_config(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 11) throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
                return NetplaneConfig(host: dco_decode_String(arr[0]),
port: dco_decode_u_16(arr[1]),
transport: dco_decode_String(arr[2]),
linkCode: dco_decode_String(arr[3]),
tunDev: dco_decode_String(arr[4]),
authkeyPath: dco_decode_String(arr[5]),
publicKeyPath: dco_decode_String(arr[6]),
privateKeyPath: dco_decode_String(arr[7]),
authPort: dco_decode_u_16(arr[8]),
loopbackRelay: dco_decode_bool(arr[9]),
noEncryption: dco_decode_bool(arr[10]),); }

@protected int dco_decode_u_16(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected int dco_decode_u_8(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected void dco_decode_unit(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return; }

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_String(deserializer);
        return AnyhowException(inner); }

@protected RustStreamSink<ConnectionEvent> sse_decode_StreamSink_connection_event_Sse(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
throw UnimplementedError('Unreachable ()'); }

@protected String sse_decode_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_list_prim_u_8_strict(deserializer);
        return utf8.decoder.convert(inner); }

@protected bool sse_decode_bool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8() != 0; }

@protected NetplaneConfig sse_decode_box_autoadd_netplane_config(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_netplane_config(deserializer)); }

@protected ConnectionEvent sse_decode_connection_event(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            var tag_ = sse_decode_i_32(deserializer);
            switch (tag_) { case 0: return ConnectionEvent_Connecting();case 1: var var_ipAddr = sse_decode_String(deserializer);
var var_netmask = sse_decode_String(deserializer);
return ConnectionEvent_Connected(ipAddr: var_ipAddr, netmask: var_netmask);case 2: return ConnectionEvent_Disconnected();case 3: var var_field0 = sse_decode_String(deserializer);
return ConnectionEvent_Error(var_field0); default: throw UnimplementedError(''); }
             }

@protected int sse_decode_i_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getInt32(); }

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected NetplaneConfig sse_decode_netplane_config(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_host = sse_decode_String(deserializer);
var var_port = sse_decode_u_16(deserializer);
var var_transport = sse_decode_String(deserializer);
var var_linkCode = sse_decode_String(deserializer);
var var_tunDev = sse_decode_String(deserializer);
var var_authkeyPath = sse_decode_String(deserializer);
var var_publicKeyPath = sse_decode_String(deserializer);
var var_privateKeyPath = sse_decode_String(deserializer);
var var_authPort = sse_decode_u_16(deserializer);
var var_loopbackRelay = sse_decode_bool(deserializer);
var var_noEncryption = sse_decode_bool(deserializer);
return NetplaneConfig(host: var_host, port: var_port, transport: var_transport, linkCode: var_linkCode, tunDev: var_tunDev, authkeyPath: var_authkeyPath, publicKeyPath: var_publicKeyPath, privateKeyPath: var_privateKeyPath, authPort: var_authPort, loopbackRelay: var_loopbackRelay, noEncryption: var_noEncryption); }

@protected int sse_decode_u_16(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint16(); }

@protected int sse_decode_u_8(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8(); }

@protected void sse_decode_unit(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.message, serializer); }

@protected void sse_encode_StreamSink_connection_event_Sse(RustStreamSink<ConnectionEvent> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.setupAndSerialize(codec: SseCodec(
            decodeSuccessData: sse_decode_connection_event,
            decodeErrorData: sse_decode_AnyhowException,
        )), serializer); }

@protected void sse_encode_String(String self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer); }

@protected void sse_encode_bool(bool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self ? 1 : 0); }

@protected void sse_encode_box_autoadd_netplane_config(NetplaneConfig self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_netplane_config(self, serializer); }

@protected void sse_encode_connection_event(ConnectionEvent self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
switch (self) { case ConnectionEvent_Connecting(): sse_encode_i_32(0, serializer); case ConnectionEvent_Connected(ipAddr: final ipAddr,netmask: final netmask): sse_encode_i_32(1, serializer); sse_encode_String(ipAddr, serializer);
sse_encode_String(netmask, serializer);
case ConnectionEvent_Disconnected(): sse_encode_i_32(2, serializer); case ConnectionEvent_Error(field0: final field0): sse_encode_i_32(3, serializer); sse_encode_String(field0, serializer);
  } }

@protected void sse_encode_i_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putInt32(self); }

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self); }

@protected void sse_encode_netplane_config(NetplaneConfig self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.host, serializer);
sse_encode_u_16(self.port, serializer);
sse_encode_String(self.transport, serializer);
sse_encode_String(self.linkCode, serializer);
sse_encode_String(self.tunDev, serializer);
sse_encode_String(self.authkeyPath, serializer);
sse_encode_String(self.publicKeyPath, serializer);
sse_encode_String(self.privateKeyPath, serializer);
sse_encode_u_16(self.authPort, serializer);
sse_encode_bool(self.loopbackRelay, serializer);
sse_encode_bool(self.noEncryption, serializer);
 }

@protected void sse_encode_u_16(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint16(self); }

@protected void sse_encode_u_8(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self); }

@protected void sse_encode_unit(void self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }
                }
                
