[package]
name = "server"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"
path = "src/server.rs"

# [[bin]]
# name = "admin"
# path = "src/admin.rs"

[dependencies]
common = { path = "../common" }
axum = { version = "0.8.1", features = ["ws"] }
log = "0.4.22"
tokio = { version = "1", features = ["full"] }
tun = { version = "0.7", features = ["async"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
tower-http = { version = "0.6.1", features = ["cors", "fs"] }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "uuid"] }
dotenv = "0.15.0"
anyhow = "1.0.98"
env_logger = "0.11.8"


[build-dependencies]
embed-resource = { version = "3.0.2", optional = true }
