name: Build client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            suffix: linux
            archive: netplane-linux.tgz
            binary: netplane
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: macos
            archive: netplane-macos.tgz
            binary: netplane
          - os: windows-latest
            suffix: windows
            archive: netplane-windows.zip
            binary: netplane.exe

    steps:
    - uses: actions/checkout@v4

    - name: Build client
      run: cargo build --release -p netplane_client --verbose

    - name: Run tests
      run: cargo test -p netplane_client --verbose

    - name: Archive binary
      shell: bash
      run: |
        mkdir -p dist
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          powershell Compress-Archive -Path target/release/${{ matrix.binary }} -DestinationPath dist/${{ matrix.archive }}
        else
          tar -czvf dist/${{ matrix.archive }} -C target/release ${{ matrix.binary }}
        fi

    - name: Upload netplane client artifact
      uses: actions/upload-artifact@v4
      with:
        name: netplane-${{ matrix.suffix }}
        path: dist/${{ matrix.archive }}

    - name: Upload artifact to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: Latest Release
        draft: true
        overwrite: true
        files: dist/${{ matrix.archive }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_NETPLANE_RELEASE_TOKEN }}
