name: Build server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: sqlite://netplane.db

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Install sqlx-cli
      run: cargo install sqlx-cli --no-default-features --features sqlite

    - name: Install musl tools
      run: sudo apt-get update && sudo apt-get install -y musl-tools

    - name: Add musl target
      run: rustup target add x86_64-unknown-linux-musl

    - name: Build server and docker image
      run: make docker

    - name: Push Docker image
      run: docker push ghcr.io/bitomia/netplane-server

    - name: Archive server binary
      shell: bash
      run: |
        mkdir -p dist
        tar -czvf dist/netplane-server.tgz -C target/x86_64-unknown-linux-musl/release netplane-server

    - name: Upload netplane server artifact
      uses: actions/upload-artifact@v4
      with:
        name: netplane-server.tgz
        path: dist/netplane-server.tgz

    - name: Upload artifact to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: Latest Release
        draft: true
        overwrite: true
        files: dist/netplane-server
      env:
        GITHUB_TOKEN: ${{ secrets.GH_NETPLANE_RELEASE_TOKEN }}
