name: Build server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build server
      run: cargo build --release -p netplane_server --verbose

    - name: Run tests
      run: cargo test -p netplane_server --verbose

    - name: Archive binary
      shell: bash
      run: |
        mkdir -p dist
        tar -czvf dist/netplane-server.tgz -C target/release netplane-server

    - name: Upload netplane server artifact
      uses: actions/upload-artifact@v4
      with:
        name: netplane-server.tgz
        path: dist/netplane-server.tgz

    - name: Upload artifact to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: Latest Release
        draft: true
        overwrite: true
        files: dist/netplane-server
      env:
        GITHUB_TOKEN: ${{ secrets.GH_NETPLANE_RELEASE_TOKEN }}
